"""add_user_onboarding_and_model_registry

Revision ID: a6b26bf4e1e8
Revises: 90a0c3539d1d
Create Date: 2026-06-16 13:37:36.388432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6b26bf4e1e8'
down_revision: Union[str, None] = '90a0c3539d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('accuracy', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('model_registry', sa.Column('last_trained', sa.String(length=50), nullable=True))
    op.add_column('model_registry', sa.Column('parameters', sa.JSON(), nullable=True))
    op.add_column('model_registry', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    op.alter_column('model_registry', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('model_registry', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('model_registry', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('model_registry', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('model_registry', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('model_registry_name_key', 'model_registry', type_='unique')
    op.drop_column('model_registry', 'weights_path')
    op.drop_column('model_registry', 'deployed_at')
    op.add_column('users', sa.Column('is_setup_complete', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'is_setup_complete')
    op.add_column('model_registry', sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('model_registry', sa.Column('weights_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.create_unique_constraint('model_registry_name_key', 'model_registry', ['name'])
    op.alter_column('model_registry', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('model_registry', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_registry', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('model_registry', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('model_registry', 'id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('model_registry', 'status')
    op.drop_column('model_registry', 'parameters')
    op.drop_column('model_registry', 'last_trained')
    op.drop_column('model_registry', 'accuracy')
    # ### end Alembic commands ###
