"""Add updated_at to ModelRegistry

Revision ID: b34c1810c744
Revises: 8a993bf3d9c5
Create Date: 2026-07-09 16:20:59.845774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34c1810c744'
down_revision: Union[str, None] = '8a993bf3d9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_registry', 'updated_at')
    # ### end Alembic commands ###
