"""Add DataMode to User and Update ModelRegistry

Revision ID: f337072baa67
Revises: 32d14ec8e2b6
Create Date: 2026-06-30 22:19:21.921823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f337072baa67'
down_revision: Union[str, None] = '32d14ec8e2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('horizon', sa.Integer(), nullable=False))
    op.add_column('model_registry', sa.Column('model_name', sa.String(length=50), nullable=False))
    op.add_column('model_registry', sa.Column('checkpoint_path', sa.String(length=255), nullable=True))
    op.add_column('model_registry', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('model_registry', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('model_registry', 'description')
    op.drop_column('model_registry', 'is_active')
    op.drop_column('model_registry', 'display_name')
    op.drop_column('model_registry', 'architecture_type')
    op.drop_column('model_registry', 'last_trained')
    op.drop_column('model_registry', 'training_metrics')
    op.drop_column('model_registry', 'name')
    op.drop_column('model_registry', 'accuracy')
    op.drop_column('model_registry', 'parameters')
    op.add_column('users', sa.Column('data_mode', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_mode')
    op.add_column('model_registry', sa.Column('parameters', sqlite.JSON(), nullable=True))
    op.add_column('model_registry', sa.Column('accuracy', sa.FLOAT(), nullable=False))
    op.add_column('model_registry', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.add_column('model_registry', sa.Column('training_metrics', sqlite.JSON(), nullable=True))
    op.add_column('model_registry', sa.Column('last_trained', sa.VARCHAR(length=50), nullable=True))
    op.add_column('model_registry', sa.Column('architecture_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('model_registry', sa.Column('display_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('model_registry', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('model_registry', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('model_registry', 'created_at')
    op.drop_column('model_registry', 'metrics')
    op.drop_column('model_registry', 'checkpoint_path')
    op.drop_column('model_registry', 'model_name')
    op.drop_column('model_registry', 'horizon')
    # ### end Alembic commands ###
